searchweather/urls.py
from django.urls import path
from searchweather import views

urlpatterns = [
    path('',views.index,name = 'index'),
    path('history/',views.history,name='history'),
]

users/urls.py
from django.urls import path
from users import views
from django.contrib.auth import views as auth_views
app_name = 'users'
urlpatterns = [
    path('login/',auth_views.LoginView.as_view(next_page='index',template_name = 'users/login.html'),name='login'),
    path('logout/', auth_views.LogoutView.as_view(next_page='index'), name='logout'),
    path('register/',views.register,name='register')
]

weather_django/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('searchweather.urls')),
    path('users/',include('users.urls')),

]

searchweather/models.py
from django.db import models
from django.contrib.auth.models import User


class SearchHistory(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    city = models.CharField(max_length=100)
    temperature = models.FloatField()
    description = models.CharField(max_length=255)
    search_date = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.city} - {self.user.username}"

users/forms.py
from django.contrib.auth.forms import AuthenticationForm,UserCreationForm
from django import forms
from django.contrib.auth.models import User

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField(required=True)

    class Meta:
        model = User
        fields = ['username', 'email', 'password1','password2']


# class UserLoginForm(AuthenticationForm):
#     pass

searchweather/views.py
from django.shortcuts import render,redirect
from searchweather.models import SearchHistory
import os
# from django.contrib.auth.decorators import login_required
import requests
# @login_required(login_url='users/login')
def index(request):
    if request.method == "POST":
        city_user = request.POST.get('city','').title().strip()
        API_KEY = os.getenv('API_KEY') # Need your api key
        res = requests.get(f"https://api.openweathermap.org/data/2.5/weather?q={city_user}&appid={API_KEY}&units=metric")
        if res.status_code == 200:
            data = res.json()
        else:
            return render(request,'searchweather/index.html',{'title':'Searching Weather'})
        weather = SearchHistory(user=request.user,city=city_user,temperature = data['main']['temp'],description = data['weather'][0]['description'])
        weather.save()
    else:
        return render(request,'searchweather/index.html',{'title':'Searching Weather'})
    context = {'weather':weather,'title':'Searching Weather'}
    return render(request,'searchweather/index.html',context)
def history(request):
    weather = SearchHistory.objects.filter(user=request.user).order_by('-search_date')
    return render(request,'searchweather/history.html',{'title':'History','weather':weather})

users/views.py
from django.shortcuts import render,redirect
from .forms import UserRegisterForm #UserLoginForm,
from django.contrib.auth import login as auth_login

# def login_view(request):
#     if request.method == "POST":
#         form = UserLoginForm(request,data=request.POST)
#         if form.is_valid():
#             user = form.get_user()
#             auth_login(request,user)
#             if user:
#                 auth_login(request,user)
#                 return redirect('index')
#         else:
#             form = UserLoginForm(request)
#     context = {'form':form}
#     return render(request,'users/login.html',context)
def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            user = form.save()
            auth_login(request,user)
            return redirect('index')
    else:
        form = UserRegisterForm()

    return render(request,'users/register.html',{'form':form,'title':'Registration'})

searchweather/templates/searchweather/base.html
<!DOCTYPE html>
{%load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <header>
    <nav>
      <a href="{% url 'index' %}">Home</a>
      {% if user.is_authenticated %}
      <a href="{% url 'history'%}">History</a>
    <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
      {% csrf_token %}
      <button type="submit" style="background:none;border:none;color:inherit;
                                 cursor:pointer;padding:0;margin:0;
                                 ">Logout</button>
    </form>
      {%else%}
      <a href="{% url 'users:login' %}">Login</a>
      <a href="{% url 'users:register' %}">Register</a>
      {%endif%}
    </nav>
  </header>
  <main>
      {% block content %}
      {% endblock content %}
  </main>
</body>
</html>

searchweather/templates/searchweather/history.html
{% extends 'searchweather/base.html' %}
{% load static %}

{%block content%}
    <h1>Search History</h1>
    <table>
      <thead>
        <tr><th>City</th><th>Date</th><th>Result</th></tr>
      </thead>
      <tbody>
      {% for w in weather %}
        <tr><td>{{w.city}}</td><td>{{w.search_date}}</td><td>{{w.temperature}}, {{w.description}}</td></tr>
      {%endfor%}
      </tbody>
    </table>
{%endblock content%}

searchweather/templates/searchweather/index.html
{% extends 'searchweather/base.html' %}

{%block content%}
    <h1>Weather Search</h1>
    {% if user.is_authenticated %}
        <p>Hello, {{user.username }}!</p>
    {%endif%}
    {% if user.is_authenticated%}
    <form action="{% url 'index' %}" method="post">
        {% csrf_token %}
      <input name='city' type="text" placeholder="Enter city..." required>
      <button type="submit">Search</button>
    </form>
    {%else%}
        <div class="alert alert-warning mt-3" role="alert">
        Only registered users can search for the weather.
    <a href="{% url 'users:login' %}" class="alert-link">Log in</a> or
    <a href="{% url 'users:register' %}" class="alert-link">sign up</a>.
        </div>
    {%endif%}
    {% if weather %}
        <h2>Weather in {{ weather.city }}:</h2>
        <p>Temperature: {{ weather.temperature }}°C</p>
        <p>Description: {{ weather.description }}</p>
    {% else %}
        <p style="color: red;">City not found.Try again</p>
    {% endif %}
{%endblock content%}

users/templates/users/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>{{title}}</title>
  <link rel="stylesheet" href="{% static 'css/styles.css' %}">
</head>
<body>
  <header>
    <nav>
      <a href="{% url 'index' %}">Home</a>
      {% if user.is_authenticated %}
      <a href="{% url 'history'%}">History</a>
    <form action="{% url 'users:logout' %}" method="post" style="display:inline;">
      {% csrf_token %}
      <button type="submit" style="background:none;border:none;color:inherit;
                                 cursor:pointer;padding:0;margin:0;
                                 ">Logout</button>
    </form>
      {%else%}
      <a href="{% url 'users:login' %}">Login</a>
      <a href="{% url 'users:register' %}">Register</a>
      {%endif%}
    </nav>
  </header>
  <main>
      {% block content %}
      {% endblock content %}
  </main>
</body>
</html>

users/templates/users/login.html
{% extends 'users/base.html' %}
{%block content%}
    <form action="{%url 'users:login' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
<!--      <input type="text" placeholder="Username" required>-->
<!--      <input type="password" placeholder="Password" required>-->
      <button type="submit">Login</button>
    </form>
{%endblock content%}

users/templates/users/register.html
{% extends 'users/base.html' %}
{%block content%}
    <form action="{% url 'users:register' %}" method="post">
        {% csrf_token %}
        {{ form.as_p }}
<!--      <input type="text" placeholder="Username" required>-->
<!--      <input type="email" placeholder="Email" required>-->
<!--      <input type="password" placeholder="Password" required>-->
      <button type="submit">Register</button>
    </form>
{%endblock content%}